### ISSUE TITLE
How to use on Windows 10

### ISSUE THREAD

**Issue by dinhanhx** [joowani/colorpedia#1]
Whenever I run `color name green` or any color cmd, it only shows this
![image](https://user-images.githubusercontent.com/38489776/105618728-420ad200-5e1d-11eb-94b5-9df134989916.png)

Then I run `color 0f`, it shows nothing.

**Comment by dinhanhx** [comment]
It works on WSL

**Comment by joowani** [comment]
Hi @dinhanhx,

Ah I didn't realize Windows already had a `color` command. 

You can play around with your user [$PATH environment variable](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/) and make sure your python scripts directory is on it. For example mine is at `C://Users/joohw/AppData/Local/Programs/Python/Python38/Scripts` but this depends on your Python environment setup.

**Comment by dinhanhx** [comment]
@joowani Thank for replying. My Python scripts directory is in PATH environment  variable but in User not in System. 

I don't really want to add any directory higher than system path. Therefore, I think I will rename your tool to `colorpedia` and reinstall it.

**Comment by joowani** [comment]
That sounds fair. I might have to rethink this and rename the command for Windows support (or provide both commands at once).

**Comment by dinhanhx** [comment]
b5b8cd354700ec7a887d378c23930d7aa1d787c9 A quick fix

**Comment by joowani** [comment]
Hey @dinhanhx,

I released 1.1.0 with `colorpedia` command. You can give that a try and let me know if you are facing any issues. Thanks.
