### ISSUE TITLE
[Feature Suggestion] Commands to manipulate user-defined palettes

### ISSUE THREAD

**Issue by dinhanhx** [joowani/colorpedia#2]
### To add a new palette, 
`colorpedia palette create <name> <path_to_json_file>`

If there is already one, ask the user if want to overwrite or not. 

### To delete a palette,
`colorpedia palette remove <name>`

**Comment by joowani** [comment]
Hi @dinhanhx,

Yes I've considered this feature before. I'm not sure the how the subcommands will look like yet (your suggested method leads to name conflicts which I'd like to avoid). But I am thinking of adding palettes.json to allow users to extend the palette list locally.

**Comment by joowani** [comment]
But I'm still not 100% sure about this feature. I'd like to encourage the users to contribute new palettes to Colorpedia instead.

**Comment by joowani** [comment]
After some thought, I've decided not to add this feature to encourage users to contribute new palettes directly to colorpedia.
