### ISSUE TITLE
Create conda package?

### ISSUE THREAD

**Issue by desilinguist** [joowani/colorpedia#6]
Fantastic package with very useful functionality! It would be great if you could also make a package for the [conda](https://docs.conda.io/en/latest/) package manager.

**Comment by joowani** [comment]
Hi @desilinguist,

Thank you! Yes I plan to add it in the near future. I'll update this issue once I do.

**Comment by joowani** [comment]
Hi @desilinguist,

I've added colorpedia to conda-forge. You can install with `conda install colorpedia -c conda-forge`!
